export const SECTOR_CODE_TO_KO: Record<string, string> = {
  '1': '건설',
  '2': '중공업',
  '3': '철강소재',
  '4': '에너지화학',
  '5': '정보통신',
  '6': '금융',
  '7': '필수소비재',
  '8': '자유소비재',
  '9': '산업재',
  'A': '건강관리',
  'B': '커뮤니케이션서비스',
  'C': '반도체',
  'D': '자동차',
  'E': '은행',
  'F': '바이오',
  'G': '미디어통신',
  '01': '건설',
  '02': '중공업',
  '03': '철강소재',
  '04': '에너지화학',
  '05': '정보통신',
  '06': '금융',
  '07': '필수소비재',
  '08': '자유소비재',
  '09': '산업재',
  '10': '건강관리',
  '11': '커뮤니케이션서비스',
  '12': '반도체',
  '13': '자동차',
  '14': '은행',
  '15': '바이오',
  '16': '미디어통신',
  '17': '철강',
  '18': '기계',
  '19': '조선',
  '20': '전기전자',
  '21': '화학',
  '22': '에너지',
  '23': '정유',
  '24': '비철금속',
  '25': '섬유',
  '26': '종이',
  '27': '광업',
  '28': '농업',
  '29': '건축',
  '30': '식품',
  '31': '의류',
  '32': '유통',
  '33': '호텔',
  '34': '서비스',
  '35': '운수',
  '36': '통신',
  '37': '제약',
  '38': '의료',
  '39': '전력',
  '40': '가스',
  '41': '폐기물',
  '42': '부동산',
  '43': '소프트웨어',
  '44': '하드웨어',
  '45': '인터넷',
  '46': '게임',
  '47': '방송',
  '48': '출판',
  '49': '교육',
  '50': '여가',
  '51': '해운',
  '52': '항공',
  '53': '철도',
  '54': '물류',
  '55': '도소매',
  '56': '증권',
  '57': '보험',
  '58': '기타금융',
  '59': '기타',
  '0000': '기타',
  '0005': '음식료품',
  '0006': '섬유의복',
  '0007': '종이목재',
  '0008': '화학',
  '0009': '의약품',
  '0010': '비철금속',
  '0011': '철강금속',
  '0012': '기계',
  '0013': '전기전자',
  '0014': '의료정밀',
  '0015': '운수장비',
  '0024': '증권',
  '0025': '보험',
  '1019': '음식료품',
  '1020': '섬유의복',
  '1021': '종이목재',
  '1022': '가구',
  '1023': '화학',
  '1024': '의약품',
  '1025': '비철금속',
  '1026': '철강금속',
  '1027': '기계',
  '1028': '전기전자',
  '1029': '의료정밀',
  '1030': '운수장비',
  '1031': '기타',
  'CG01': '음식료품',
  'CG02': '섬유의복',
  'CG03': '종이목재',
  'CG04': '화학',
  'CG05': '의약품',
  'CG06': '비철금속',
  'CG07': '철강금속',
  'CG08': '기계',
  'CG09': '전기전자',
  'CG10': '의료정밀',
  'CG11': '운수장비',
  'CG12': '건설',
  'CG13': '유통',
  'CG14': '운수창고',
  'CG15': '방송통신',
  'CG16': '금융',
  'CG17': 'IT',
  'CG18': '전기가스',
  'CG19': '서비스',
  'CG20': '정유',
  'CG21': '철강',
  'CG22': '반도체',
  'CG23': '건축',
  'CG24': '자동차',
  'CG25': '조선',
  'CG26': '농업임업어업',
  '0111': '농업임업어업',
  '0121': '광업',
  '0131': '음식료품',
  '0141': '섬유의복',
  '0151': '종이목재',
  '0159': '가구',
  '0161': '화학',
  '0171': '의약품',
  '0181': '비철금속',
  '0191': '철강금속',
  '0201': '기계',
  '0211': '전기전자',
  '0221': '의료정밀',
  '0231': '운수장비',
  '0241': '건설',
  '0251': '유통',
  '0261': '운수창고',
  '0271': '방송통신',
  '0281': '금융',
  '0291': 'IT',
  '0301': '전기가스',
  '0311': '서비스',
  '0321': '정유',
  '0331': '철강',
  '0341': '반도체',
  '0351': '건축',
  '0361': '자동차',
  '0371': '조선',
  '0381': '가스',
  '0391': '부동산',
  '0401': '소프트웨어',
  '0411': '하드웨어',
  '0421': '인터넷',
  '0431': '게임',
  '0441': '방송',
  '0451': '출판',
  '0461': '교육',
  '0471': '여가',
  '0481': '해운',
  '0491': '항공',
  '0501': '철도',
  '0511': '물류',
  '0521': '도소매',
  '0531': '증권',
  '0541': '보험',
  '0551': '기타금융',
  '0561': '호텔',
  '0571': '레저',
  '0581': '환경',
  '0591': '기타',
};

export function resolveSectorDisplay(sector: string): string {
  return SECTOR_CODE_TO_KO[sector] ?? sector;
}

export const SECTOR_KO_TO_EN: Record<string, string> = {
  '건설': 'Construction',
  '중공업': 'Heavy Industry',
  '철강소재': 'Steel & Materials',
  '에너지화학': 'Energy & Chemicals',
  '정보통신': 'IT & Telecom',
  '금융': 'Financials',
  '필수소비재': 'Consumer Staples',
  '자유소비재': 'Consumer Discretionary',
  '산업재': 'Industrials',
  '건강관리': 'Healthcare',
  '커뮤니케이션서비스': 'Communication Services',
  '반도체': 'Semiconductors',
  '자동차': 'Automobiles',
  '은행': 'Banks',
  '바이오': 'Biotech',
  '미디어통신': 'Media & Telecom',
  '증권': 'Securities',
  '보험': 'Insurance',
  '운송': 'Transportation',
  '선박': 'Ships',
  '기계': 'Machinery',
  '전기전자': 'Electronics',
  '철강': 'Steel',
  '에너지': 'Energy',
  '화학': 'Chemicals',
  '건축': 'Building',
  '식품': 'Food',
  '의류': 'Apparel',
  '유통': 'Retail',
  '호텔': 'Hotels',
  '서비스': 'Services',
  '운수': 'Transport',
  '통신': 'Telecom',
  '제약': 'Pharmaceuticals',
  '의료': 'Medical',
  '농업': 'Agriculture',
  '광업': 'Mining',
  '전력': 'Electric Power',
  '가스': 'Gas',
  '폐기물': 'Waste Management',
  '부동산': 'Real Estate',
  '소프트웨어': 'Software',
  '하드웨어': 'Hardware',
  '인터넷': 'Internet',
  '게임': 'Gaming',
  '방송': 'Broadcasting',
  '출판': 'Publishing',
  '교육': 'Education',
  '여가': 'Leisure',
  '섬유': 'Textiles',
  '종이': 'Paper',
  '비철금속': 'Non-ferrous Metals',
  '정유': 'Refining',
  '해운': 'Shipping',
  '항공': 'Airlines',
  '철도': 'Railways',
  '물류': 'Logistics',
  '도소매': 'Wholesale & Retail',
  'IT': 'IT',
  '기타금융': 'Other Financials',
  '기타': 'Other',
  '음식료품': 'Food & Beverages',
  '섬유의복': 'Textiles & Apparel',
  '종이목재': 'Paper & Wood',
  '의약품': 'Pharmaceuticals',
  '철강금속': 'Steel & Metals',
  '의료정밀': 'Medical & Precision',
  '운수장비': 'Transport Equipment',
  '운수창고': 'Transport & Storage',
  '방송통신': 'Broadcasting & Telecom',
  '전기가스': 'Electricity & Gas',
  '농업임업어업': 'Agriculture Forestry Fishery',
  '가구': 'Furniture',
  '레저': 'Leisure',
  '환경': 'Environment',
};

export const SECTOR_EN_TO_KO: Record<string, string> = Object.fromEntries(
  Object.entries(SECTOR_KO_TO_EN).map(([ko, en]) => [en, ko])
);

export function translateSector(sector: string, lang: 'ko' | 'en'): string {
  if (lang === 'en') return SECTOR_KO_TO_EN[sector] ?? sector;
  return SECTOR_EN_TO_KO[sector] ?? sector;
}